from core.views.administration import (
    AdminFeedbackListView,
    AdminIssueListView,
    AdminIssueUpdateView,
    AdminLoginView,
    AdminProductDetailView,
    AdminProductListCreateView,
)
from core.views.aggregations import (
    AnomaliesView,
    AnomalyResolveView,
    CategoryBreakdownView,
    MonthlySummariesView,
    NetWorthView,
    RecurringChargesView,
    SpendingInsightsView,
    StabilityScoreView,
    TransactionDetailView,
    TransactionListCreateView,
)
from core.views.auth import LoginView, LogoutView, RefreshView, SignupView
from core.views.budgets import (
    BudgetHistoryView,
    BudgetProgressView,
    BudgetView,
    DashboardGoalView,
    DashboardView,
    SavingsProgressView,
    StarterTemplatesView,
)
from core.views.conversations import (
    ConversationAttachmentsView,
    ConversationDetailView,
    ConversationListCreateView,
    ConversationMessagesView,
)
from core.views.feedback import FeedbackCreateView, IssueListCreateView
from core.views.health import db_check, health, ping
from core.views.profile import (
    BankAccountDetailView,
    BankAccountListCreateView,
    MeConsentRevokeView,
    MeConsentView,
    MePreferencesView,
    MeView,
)
from core.views.recommendation import RecommendationFeedbackView, RecommendationsView
from core.views.statements import (
    StatementDetailView,
    StatementListCreateView,
    StatementNormalizedView,
    StatementOcrResultView,
)

__all__ = [
    "health",
    "db_check",
    "ping",
    "SignupView",
    "LoginView",
    "RefreshView",
    "LogoutView",
    "MeView",
    "MePreferencesView",
    "MeConsentView",
    "MeConsentRevokeView",
    "BankAccountListCreateView",
    "BankAccountDetailView",
    "StatementListCreateView",
    "StatementDetailView",
    "StatementOcrResultView",
    "StatementNormalizedView",
    "TransactionListCreateView",
    "TransactionDetailView",
    "MonthlySummariesView",
    "CategoryBreakdownView",
    "RecurringChargesView",
    "AnomaliesView",
    "AnomalyResolveView",
    "SpendingInsightsView",
    "NetWorthView",
    "StabilityScoreView",
    "BudgetView",
    "BudgetHistoryView",
    "BudgetProgressView",
    "SavingsProgressView",
    "StarterTemplatesView",
    "DashboardView",
    "DashboardGoalView",
    "ConversationListCreateView",
    "ConversationDetailView",
    "ConversationMessagesView",
    "ConversationAttachmentsView",
    "FeedbackCreateView",
    "IssueListCreateView",
    "RecommendationsView",
    "RecommendationFeedbackView",
    "AdminLoginView",
    "AdminFeedbackListView",
    "AdminIssueListView",
    "AdminIssueUpdateView",
    "AdminProductListCreateView",
    "AdminProductDetailView",
]
