# Generated by Django 6.0.6 on 2026-07-07 15:29

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(default='reviewer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('masked_account_number', models.CharField(max_length=50)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Plan', max_length=255)),
                ('period_type', models.CharField(default='monthly', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('selected_template_key', models.CharField(blank=True, max_length=50, null=True)),
                ('savings_goal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('goal_target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('goal_timeline_months', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('features', models.JSONField(blank=True, null=True)),
                ('external_link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('income_bracket', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, max_length=14, null=True)),
                ('income_steadiness', models.CharField(blank=True, max_length=20, null=True)),
                ('dependents_count', models.SmallIntegerField(default=0)),
                ('onboarding_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='BankStatementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('layout_signature', models.CharField(max_length=255)),
                ('column_mapping_json', models.JSONField()),
                ('date_format', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_statement_templates',
                'constraints': [models.UniqueConstraint(fields=('bank_name', 'layout_signature'), name='unique_bank_layout_signature')],
            },
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_values', models.JSONField()),
                ('changed_via', models.CharField(default='dashboard', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='core.budget')),
            ],
            options={
                'db_table': 'budget_history',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('stage', models.CharField(default='general', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.message')),
            ],
            options={
                'db_table': 'message_references',
            },
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statements', to='core.product')),
            ],
            options={
                'db_table': 'problem_statements',
            },
        ),
        migrations.CreateModel(
            name='StatementFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seaweed_file_id', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('start_transaction_date', models.DateField(blank=True, null=True)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_files', to='core.bankaccount')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_files', to='core.bankstatementtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_files', to='core.user')),
            ],
            options={
                'db_table': 'statement_files',
            },
        ),
        migrations.CreateModel(
            name='StatementNormalized',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_json', models.JSONField()),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.statementfile')),
            ],
            options={
                'db_table': 'statement_normalized',
            },
        ),
        migrations.CreateModel(
            name='StatementOcrResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seaweed_file_id', models.CharField(max_length=255)),
                ('ocr_engine', models.CharField(default='MinerU', max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='core.statementfile')),
            ],
            options={
                'db_table': 'statement_ocr_results',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('merchant_raw', models.CharField(blank=True, max_length=500, null=True)),
                ('merchant_normalized', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('source', models.CharField(default='statement', max_length=20)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_fields', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankaccount')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.statementfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.user')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('severity', models.CharField(max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='core.transaction')),
            ],
            options={
                'db_table': 'anomaly_flags',
            },
        ),
        migrations.CreateModel(
            name='SpendingPatternInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(max_length=50)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('value_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_insights', to='core.user')),
            ],
            options={
                'db_table': 'spending_pattern_insights',
            },
        ),
        migrations.CreateModel(
            name='ReportedIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='core.user')),
            ],
            options={
                'db_table': 'reported_issues',
            },
        ),
        migrations.CreateModel(
            name='RecurringCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_normalized', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=20)),
                ('avg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_occurrence_date', models.DateField(blank=True, null=True)),
                ('next_expected_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_charges', to='core.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_charges', to='core.user')),
            ],
            options={
                'db_table': 'recurring_charges',
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_query', models.TextField(blank=True, null=True)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='core.user')),
            ],
            options={
                'db_table': 'recommendation_logs',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.user')),
            ],
            options={
                'db_table': 'reactions',
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('total_across_accounts', models.DecimalField(decimal_places=2, max_digits=14)),
                ('per_account_breakdown_json', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to='core.user')),
            ],
            options={
                'db_table': 'net_worth_snapshots',
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('total_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('category_breakdown_json', models.JSONField(blank=True, null=True)),
                ('top_merchants_json', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='core.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='core.user')),
            ],
            options={
                'db_table': 'monthly_summaries',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.user'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(max_length=50)),
                ('policy_version', models.CharField(max_length=20)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='core.user')),
            ],
            options={
                'db_table': 'consent_records',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='core.user'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.user'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('currency_display_format', models.CharField(default='symbol', max_length=20)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('budget_cycle_start_day', models.SmallIntegerField(default=1)),
                ('default_view', models.CharField(default='monthly', max_length=20)),
                ('retain_raw_documents', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.user')),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('allocated_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.budget')),
            ],
            options={
                'db_table': 'budget_allocations',
                'constraints': [models.UniqueConstraint(fields=('budget', 'category'), name='unique_budget_category')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_messages_conversation'),
        ),
        migrations.AddIndex(
            model_name='messagereference',
            index=models.Index(fields=['target_type', 'target_id'], name='idx_message_references_target'),
        ),
        migrations.AddIndex(
            model_name='problemstatement',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='idx_problem_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['severity', 'resolved'], name='idx_anomaly_flags_severity'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='idx_transactions_user_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='idx_transactions_user_category'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account'], name='idx_transactions_account'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='idx_transactions_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('user', 'account', 'transaction_date', 'amount', 'merchant_raw'), name='unique_ledger_transaction_match'),
        ),
        migrations.AddIndex(
            model_name='statementfile',
            index=models.Index(fields=['user', 'status'], name='idx_statement_user_status'),
        ),
        migrations.AddConstraint(
            model_name='statementfile',
            constraint=models.UniqueConstraint(fields=('user', 'checksum'), name='unique_user_statement_checksum'),
        ),
        migrations.AddIndex(
            model_name='spendingpatterninsight',
            index=models.Index(fields=['user', 'insight_type'], name='idx_user_spending_type'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', 'shown_at'], name='idx_recommendation_logs_user'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['target_type', 'target_id'], name='idx_reactions_target'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(('rating__range', (1, 5))), name='chk_reaction_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='networthsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'as_of_date'), name='unique_user_net_worth_date'),
        ),
        migrations.AddIndex(
            model_name='monthlysummary',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='idx_summaries_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='monthlysummary',
            constraint=models.UniqueConstraint(fields=('user', 'account', 'month'), name='unique_user_month_summary'),
        ),
    ]
