# Generated by Django 6.0.6 on 2026-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message_widget_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementfile",
            name="failed_phase",
            field=models.CharField(
                blank=True,
                choices=[("extraction", "Extraction"), ("normalization", "Normalization")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="statementfile",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statementfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_extraction", "Pending extraction"),
                    ("pending_normalization", "Pending normalization"),
                    ("pending_approval", "Pending approval"),
                    ("processed", "Processed"),
                ],
                default="pending_extraction",
                max_length=30,
            ),
        ),
    ]
