# Generated by Django 6.0.6 on 2026-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_statementfile_failed_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementfile",
            name="is_processing",
            field=models.BooleanField(default=False),
        ),
    ]
