# Generated by Django 6.0.6 on 2026-07-09 20:19

from django.db import migrations, models

# Drops the "pending_" prefix (is_processing already conveys "actively
# running", so it was redundant baked into the status name too) — renames
# any existing rows so no historical data is stranded on the old values.
_RENAMES = {
    "pending_extraction": "extraction",
    "pending_normalization": "normalization",
    "pending_approval": "approval",
}


def rename_forward(apps, schema_editor):
    StatementFile = apps.get_model("core", "StatementFile")
    for old_value, new_value in _RENAMES.items():
        StatementFile.objects.filter(status=old_value).update(status=new_value)


def rename_backward(apps, schema_editor):
    StatementFile = apps.get_model("core", "StatementFile")
    for old_value, new_value in _RENAMES.items():
        StatementFile.objects.filter(status=new_value).update(status=old_value)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_statementfile_is_processing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("extraction", "Extraction"),
                    ("normalization", "Normalization"),
                    ("approval", "Approval"),
                    ("processed", "Processed"),
                ],
                default="extraction",
                max_length=30,
            ),
        ),
        migrations.RunPython(rename_forward, rename_backward),
    ]
