# Generated by Django 6.0.6 on 2026-07-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_statementfile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementfile",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statementfile",
            name="file_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
