# Generated by Django 6.0.6 on 2026-07-10 09:44

from django.db import migrations, models

# Renames each status to name the phase already completed, rather than the
# phase pending — and disambiguates the terminal state from the "approve"
# action name (old "approval" meant "awaiting approval", which read as the
# same word as the action that resolves it). Renames any existing rows so
# no historical data is stranded on the old values. Note this is NOT a
# straight positional swap: the old "awaiting approval" state (`approval`)
# becomes `normalized`, and the old terminal state (`processed`) becomes
# `approved`.
_RENAMES = {
    "extraction": "uploaded",
    "normalization": "extracted",
    "approval": "normalized",
    "processed": "approved",
}


def rename_forward(apps, schema_editor):
    StatementFile = apps.get_model("core", "StatementFile")
    for old_value, new_value in _RENAMES.items():
        StatementFile.objects.filter(status=old_value).update(status=new_value)


def rename_backward(apps, schema_editor):
    StatementFile = apps.get_model("core", "StatementFile")
    for old_value, new_value in _RENAMES.items():
        StatementFile.objects.filter(status=new_value).update(status=old_value)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_statementfile_file_size_statementfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("extracted", "Extracted"),
                    ("normalized", "Normalized"),
                    ("approved", "Approved"),
                ],
                default="uploaded",
                max_length=30,
            ),
        ),
        migrations.RunPython(rename_forward, rename_backward),
    ]
