# Generated by Django 6.0.6 on 2026-07-11 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_statementfile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="goal_target_amount",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="goal_timeline_months",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="savings_goal_name",
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("timeline_months", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "goals",
            },
        ),
    ]
