# Generated by Django 6.0.6 on 2026-07-15 15:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_grant_ai_readonly_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemstatement",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
