# Generated by Django 6.0.6 on 2026-07-15 15:16

import uuid
from django.db import migrations, models

# Starter set for the categories table. Exactly one row per category_type MUST
# have is_fallback=True (enforced by the unique_fallback_per_type constraint
# below) — resolve_category() (core/models/categories/resolution.py) relies on
# there being exactly one to fall back to per debit/credit direction.
CATEGORY_SEED_DATA: list[dict] = [
    {"name": "housing", "label": "Housing", "category_type": "expense", "is_fallback": False},
    {"name": "food", "label": "Food", "category_type": "expense", "is_fallback": False},
    {"name": "transport", "label": "Transport", "category_type": "expense", "is_fallback": False},
    {"name": "savings", "label": "Savings", "category_type": "expense", "is_fallback": False},
    {
        "name": "lifestyle",
        "label": "Lifestyle",
        "category_type": "expense",
        "is_fallback": False,
    },
    {"name": "other", "label": "Other", "category_type": "expense", "is_fallback": True},
    {"name": "salary", "label": "Salary", "category_type": "income", "is_fallback": False},
    {
        "name": "transfers_in",
        "label": "Transfers In",
        "category_type": "income",
        "is_fallback": False,
    },
    {
        "name": "other_income",
        "label": "Other Income",
        "category_type": "income",
        "is_fallback": True,
    },
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Category.objects.bulk_create(Category(**row) for row in CATEGORY_SEED_DATA)


def remove_seeded_categories(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Category.objects.filter(name__in=[row["name"] for row in CATEGORY_SEED_DATA]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_problemstatement_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("category_type", models.CharField(max_length=20)),
                ("is_fallback", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "categories",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_fallback", True)),
                        fields=("category_type",),
                        name="unique_fallback_per_type",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_categories, remove_seeded_categories),
    ]
