# Hand-authored (not autogenerated): AnomalyFlag.user is added as a
# required field to a table with existing rows (seed data), which needs a
# real backfill from transaction.user rather than an arbitrary one-off
# default — `makemigrations` can only prompt for the latter interactively,
# so this migration adds the field nullable, backfills it via RunPython,
# then tightens it to NOT NULL to match the model.

import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_anomaly_flag_user(apps, schema_editor):
    # QuerySet.update() can't reference a joined field directly, and this
    # only ever runs over however many rows seed data produced — a per-row
    # loop is simplest and clearest for a one-off backfill like this.
    AnomalyFlag = apps.get_model("core", "AnomalyFlag")
    for anomaly in AnomalyFlag.objects.filter(
        user__isnull=True, transaction__isnull=False
    ).select_related("transaction"):
        anomaly.user_id = anomaly.transaction.user_id
        anomaly.save(update_fields=["user"])


def noop_reverse(apps, schema_editor):
    # No reverse backfill needed — AnomalyFlag.user is dropped entirely by
    # the RemoveField this migration's reverse runs afterward.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_convert_category_to_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider_slug", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_otp", "pending_otp"),
                            ("linked", "linked"),
                            ("revoked", "revoked"),
                            ("failed", "failed"),
                        ],
                        default="pending_otp",
                        max_length=20,
                    ),
                ),
                ("external_customer_id", models.CharField(blank=True, max_length=255, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("oauth_state", models.CharField(blank=True, max_length=255, null=True)),
                ("error_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_connections",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "bank_connections",
            },
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(
                fields=["user", "provider_slug"], name="idx_bank_conn_user_provider"
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="link_type",
            field=models.CharField(
                choices=[("manual", "manual"), ("synced", "synced")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="external_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_accounts",
                to="core.bankconnection",
            ),
        ),
        migrations.AlterField(
            model_name="anomalyflag",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomaly_flags",
                to="core.transaction",
            ),
        ),
        migrations.AddField(
            model_name="anomalyflag",
            name="user",
            field=models.ForeignKey(
                null=True,  # tightened to NOT NULL below, after the backfill
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomaly_flags",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="anomalyflag",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomaly_flags",
                to="core.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="anomalyflag",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="anomalyflag",
            name="month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anomalyflag",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.RunPython(backfill_anomaly_flag_user, noop_reverse),
        migrations.AlterField(
            model_name="anomalyflag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomaly_flags",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("statement", "statement"),
                    ("manual", "manual"),
                    ("synced", "synced"),
                ],
                default="statement",
                max_length=20,
            ),
        ),
    ]
