# Generated by Django 6.0.6 on 2026-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_bank_integration"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("connection__isnull", False)),
                fields=("connection", "external_account_id"),
                name="unique_external_account_per_connection",
            ),
        ),
    ]
