# Generated by Django 6.0.6 on 2026-07-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_bank_account_external_id_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bankconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "linked")),
                fields=("user", "provider_slug"),
                name="unique_active_bank_connection_per_user_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_customer_id__isnull", False)),
                fields=("provider_slug", "external_customer_id"),
                name="unique_bank_customer_identity",
            ),
        ),
    ]
