# Generated by Django 6.0.6 on 2026-07-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_bankaccount_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="merchant_raw",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
