# Generated by Django 6.0.6 on 2026-08-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260816_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='suggestions_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
