# Generated by Django 6.0.6 on 2026-08-26 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_include_direction_in_transaction_duplicate_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(max_length=100, unique=True)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("fund", "Investment fund"),
                            ("currency", "Currency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_symbol", models.CharField(max_length=120)),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("spot", "Spot price"),
                            ("nav", "Net asset value"),
                            ("customer_buy_rate", "Customer buy rate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("price_currency", models.CharField(default="EGP", max_length=3)),
                ("unit", models.CharField(max_length=40)),
                (
                    "minimum_increment",
                    models.DecimalField(decimal_places=8, default=1, max_digits=20),
                ),
                ("fractional_units_supported", models.BooleanField(default=False)),
                ("max_quote_age_seconds", models.PositiveIntegerField(default=3600)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_instrument",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "db_table": "investment_instruments",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("minimum_increment__gt", 0)),
                        name="investment_instrument_increment_gt_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_quote_age_seconds__gt", 0)),
                        name="investment_instrument_quote_age_gt_zero",
                    ),
                ],
            },
        ),
    ]
