# Generated by Django 6.0.6 on 2026-08-26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_investment_instruments"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedInvestmentScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="Investment scenario", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("saved", "Saved"), ("archived", "Archived")],
                        default="saved",
                        max_length=20,
                    ),
                ),
                ("payload_json", models.JSONField()),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_investment_scenario",
                        to="core.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_investment_scenarios",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "saved_investment_scenarios",
                "ordering": ["-saved_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "saved_at"],
                        name="idx_saved_scenario_user",
                    )
                ],
            },
        ),
    ]
