# Generated by Django 6.0.6 on 2026-08-27 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_investment_holdings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedInvestmentAllocationPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=24)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("fees", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("purchased_at", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "holding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_plan_purchases",
                        to="core.investmentholding",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_plan_purchases",
                        to="core.investmentinstrument",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_purchases",
                        to="core.savedinvestmentscenario",
                    ),
                ),
            ],
            options={
                "db_table": "saved_investment_allocation_purchases",
                "ordering": ["recorded_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario", "instrument"),
                        name="saved_scenario_instrument_purchase_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="saved_purchase_quantity_gt_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_price__gt", 0)),
                        name="saved_purchase_unit_price_gt_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fees__gte", 0)), name="saved_purchase_fees_gte_zero"
                    ),
                ],
            },
        ),
    ]
