# Generated by Django 6.0.6 on 2026-08-27 21:32

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_saved_plan_purchase_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlysummary",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
