# Generated by Django 6.0.6 on 2026-08-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_reduce_embedding_dimensions_to_768"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="thinking_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
