"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# ── Fail-fast env validation ──────────────────────────────────────────────────
# The app refuses to start if any required env var is missing. This surfaces
# misconfigurations immediately rather than at first DB query or API call.
_REQUIRED_ENV = [
    "POSTGRES_DB",
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
    "AI_SERVICE_TOKEN",
    "SEAWEED_S3_ENDPOINT",
    "SEAWEED_ACCESS_KEY",
    "SEAWEED_SECRET_KEY",
]
_missing = [v for v in _REQUIRED_ENV if not os.environ.get(v)]
if _missing:
    raise RuntimeError(
        f"Missing required environment variables: {', '.join(_missing)}. "
        "Copy .env.example to .env and fill in the values."
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    # API
    "corsheaders",  # django-cors-headers (Phase 1 — dev wiring)
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",  # backs POST /auth/logout (see core/views/auth.py)
    "drf_spectacular",
    "django_extensions",  # show_urls, shell_plus, etc.
    "storages",  # django-storages (S3/SeaweedFS backend)
    # Project apps
    "core",
]

# core.User is the auth model for the whole project (see PLAN.md Checkpoint 0)
# — AdminUser (Administration domain) is deliberately NOT wired in here, since
# it's a structurally separate credential space (API Design Guidelines §8).
AUTH_USER_MODEL = "core.User"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Every endpoint requires a valid JWT by default (API Design Guidelines §8);
    # individual views (signup/login/refresh, and the health/ping/ask dev probes)
    # opt out explicitly with AllowAny rather than the API being open by default.
    # UserJWTAuthentication (not simplejwt's raw JWTAuthentication) explicitly
    # rejects admin tokens — see core/authentication.py's module docstring —
    # so a token issued to an AdminUser can never authenticate as a regular
    # user here, structurally, not just because the two id spaces happen not
    # to collide. /admin/* views override this with AdminJWTAuthentication
    # (core/permissions.py's AdminAuthMixin).
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.UserJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Wraps every DRF error response into the single shared shape from
    # API Design Guidelines §10, and reclassifies serializer ValidationErrors
    # as 422 (semantic/business-rule failures) rather than DRF's default 400 —
    # see core/exceptions.py for the full rationale.
    "EXCEPTION_HANDLER": "core.exceptions.api_exception_handler",
    # DRF's LimitOffsetPagination only activates when it can resolve a limit;
    # with PAGE_SIZE unset (None), a request with no explicit ?limit= param
    # gets no pagination at all — a bare array instead of the documented
    # {count,next,previous,results} envelope (API Design Guidelines §5).
    # Setting this makes every view using LimitOffsetPagination consistently
    # paginated by default, matching every endpoint documented as
    # "Pagination: Offset" in the Data Shapes docs.
    "PAGE_SIZE": 20,
}

# rest_framework.W001 warns about PAGE_SIZE with no DEFAULT_PAGINATION_CLASS —
# that's deliberate here: some endpoints (e.g. GET /accounts, GET
# /analytics/net-worth) are intentionally unpaginated (small, bounded,
# per-user collections — see core/views/profile.py's BankAccountListCreateView
# docstring), so pagination is opted into per-view via `pagination_class`
# rather than applied globally.
SILENCED_SYSTEM_CHECKS = ["rest_framework.W001"]

SPECTACULAR_SETTINGS = {
    "TITLE": "NBE Financial Advisor API",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    # Short-lived access token + longer-lived, rotating refresh token — standard
    # JWT bearer pair per API Design Guidelines §8. Rotation + blacklist-after-
    # rotation means a stolen refresh token can only be replayed once before
    # it's rejected, without needing a separate revocation list to maintain by hand.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ── Refresh-token cookie (hybrid httpOnly approach, PLAN.md Checkpoint E) ──
# Only the refresh token moves to an httpOnly cookie — the access token
# stays in the response body/Authorization header (explicit decision: ease
# of dev/Swagger testing). SameSite=Lax works in both dev (frontend :5173,
# backend :8000 — cross-origin but same-SITE, since SameSite matching is by
# scheme+registrable-domain, not port) and prod (frontend/backend share one
# origin behind nginx, deploy/nginx.conf) without needing SameSite=None.
# Secure is tied to DEBUG since dev has no TLS — a Secure cookie would just
# be silently dropped over plain http://localhost.
REFRESH_TOKEN_COOKIE_NAME = "refresh_token"
REFRESH_TOKEN_COOKIE_SECURE = not DEBUG
REFRESH_TOKEN_COOKIE_SAMESITE = "Lax"
REFRESH_TOKEN_COOKIE_MAX_AGE = int(SIMPLE_JWT["REFRESH_TOKEN_LIFETIME"].total_seconds())

MIDDLEWARE = [
    # CorsMiddleware must be first — before any middleware that can generate
    # responses (SecurityMiddleware, CommonMiddleware) so preflight OPTIONS
    # requests get the CORS headers before being short-circuited.
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ── CORS (django-cors-headers) ─────────────────────────────────────────────────
# Covers the Vite dev server (:5173) and the deploy nginx proxy (:8080).
# In production, DJANGO_CORS_ALLOWED_ORIGINS should be set to the real domain.
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://localhost:8080,http://127.0.0.1:5173",
    ).split(",")
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "appdb"),
        "USER": os.environ.get("POSTGRES_USER", "appuser"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "apppass"),
        "HOST": os.environ.get("POSTGRES_HOST", "postgres"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# File storage — SeaweedFS via its S3-compatible Filer gateway
# (docs/File_System_Structure.md, PLAN.md Checkpoint 0). One named storage
# per bucket/file-type — services/storage_backends.py owns the connection
# details read from the SEAWEED_* env vars above (_REQUIRED_ENV). "default"
# stays FileSystemStorage since nothing in this project uses Django's generic
# FileField storage; every real upload path picks one of the named storages
# below explicitly via services/file_storage.py.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "raw_statements": {
        "BACKEND": "services.storage_backends.RawStatementStorage",
    },
    "ocr_artifacts": {
        "BACKEND": "services.storage_backends.OcrArtifactStorage",
    },
    "normalized_artifacts": {
        "BACKEND": "services.storage_backends.NormalizedArtifactStorage",
    },
    "reference_data": {
        "BACKEND": "services.storage_backends.ReferenceDataStorage",
    },
}
