"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the project-root .env into os.environ once. override=False → real env /
# Compose-injected vars always win (safe in Docker & prod), while host-run
# (python manage.py, pytest, celery -A config) gets the .env values nothing
# else provides.
environ.Env.read_env(BASE_DIR / ".env")

# ── Required env vars (fail-fast) ─────────────────────────────────────────────
# Each read below has no default, so django-environ raises ImproperlyConfigured
# immediately if any is missing — surfacing misconfigurations at startup rather
# than at first DB query or API call. They're consumed elsewhere
# (services/storage_backends.py, core/ask_view.py) but are read here too so
# every required var is validated in one place. AI_READONLY_PASSWORD is
# intentionally NOT required here: only core/migrations/0009_grant_ai_readonly_role.py
# consumes it (during `migrate`), reading os.environ directly then — so
# `check`/`runserver`/`test` must not need it.
SEAWEED_S3_ENDPOINT = env.str("SEAWEED_S3_ENDPOINT")
SEAWEED_ACCESS_KEY = env.str("SEAWEED_ACCESS_KEY")
SEAWEED_SECRET_KEY = env.str("SEAWEED_SECRET_KEY")
AI_SERVICE_TOKEN = env.str("AI_SERVICE_TOKEN")
# Has a default; consumed by core/ask_view.py.
AI_SERVICE_URL = env.str("AI_SERVICE_URL", "http://ai-service:8001")
# Toggles services/ai_service.py's dispatch functions between an in-process
# mock and a real HTTP call to AI_SERVICE_URL — same pattern as the AI
# service's own USE_MOCK_LLM/USE_MOCK_MINERU. Defaults on so dev/test runs
# never need a live ai-service; flip to 0 once one is reachable.
USE_MOCK_AI_SERVICE = env.bool("USE_MOCK_AI_SERVICE", True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("DJANGO_SECRET_KEY", "dev-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["*"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    # API
    "corsheaders",  # django-cors-headers (Phase 1 — dev wiring)
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",  # backs POST /auth/logout (see core/views/auth.py)
    "drf_spectacular",
    "django_extensions",  # show_urls, shell_plus, etc.
    "storages",  # django-storages (S3/SeaweedFS backend)
    "django_filters",  # FilterSets for query-param filtering (PLAN.md Checkpoint F)
    # Project apps
    "core",
]

# core.User is the auth model for the whole project (see PLAN.md Checkpoint 0)
# — AdminUser (Administration domain) is deliberately NOT wired in here, since
# it's a structurally separate credential space (API Design Guidelines §8).
AUTH_USER_MODEL = "core.User"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Every endpoint requires a valid JWT by default (API Design Guidelines §8);
    # individual views (signup/login/refresh, and the health/ping/ask dev probes)
    # opt out explicitly with AllowAny rather than the API being open by default.
    # UserJWTAuthentication (not simplejwt's raw JWTAuthentication) explicitly
    # rejects admin tokens — see core/authentication.py's module docstring —
    # so a token issued to an AdminUser can never authenticate as a regular
    # user here, structurally, not just because the two id spaces happen not
    # to collide. /admin/* views override this with AdminJWTAuthentication
    # (core/permissions.py's AdminAuthMixin).
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.UserJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Wraps every DRF error response into the single shared shape from
    # API Design Guidelines §10, and reclassifies serializer ValidationErrors
    # as 422 (semantic/business-rule failures) rather than DRF's default 400 —
    # see core/exceptions.py for the full rationale.
    "EXCEPTION_HANDLER": "core.exceptions.api_exception_handler",
    # DRF's LimitOffsetPagination only activates when it can resolve a limit;
    # with PAGE_SIZE unset (None), a request with no explicit ?limit= param
    # gets no pagination at all — a bare array instead of the documented
    # {count,next,previous,results} envelope (API Design Guidelines §5).
    # Setting this makes every view using LimitOffsetPagination consistently
    # paginated by default, matching every endpoint documented as
    # "Pagination: Offset" in the Data Shapes docs.
    "PAGE_SIZE": 20,
}

# rest_framework.W001 warns about PAGE_SIZE with no DEFAULT_PAGINATION_CLASS —
# that's deliberate here: some endpoints (e.g. GET /accounts, GET
# /analytics/net-worth) are intentionally unpaginated (small, bounded,
# per-user collections — see core/views/profile.py's BankAccountListCreateView
# docstring), so pagination is opted into per-view via `pagination_class`
# rather than applied globally.
SILENCED_SYSTEM_CHECKS = ["rest_framework.W001"]

# Base path Swagger UI/Redoc prepend to every "Try it out" request. Django's
# own urlpatterns (core.urls) carry no "/api" prefix — only deploy/nginx.conf
# adds one, stripping it back off before forwarding (deploy/docker-compose.yml
# sets this to "/api" on the backend service to match). Left empty (the
# default, matching dev's docker-compose.yml, which publishes this service
# directly with no reverse proxy in front) means requests go straight to the
# path drf-spectacular already documents — exactly what an unprefixed
# core.urls route needs.
API_URL_PREFIX = env.str("API_URL_PREFIX", "")

SPECTACULAR_SETTINGS = {
    "TITLE": "NBE Financial Advisor API",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVERS": [{"url": API_URL_PREFIX}] if API_URL_PREFIX else [],
    # Three unrelated fields are all named "status" with different choice
    # sets (StatementFile's pipeline-phase status, the statements pipeline's
    # PATCH/POST advance-target subset, and admin issue triage status) —
    # left alone, drf-spectacular's automatic enum-component naming collides
    # all three into one "Status" name and disambiguates with unreadable
    # hash suffixes (e.g. StatusC7eEnum). Naming each explicitly keeps the
    # generated schema/Swagger UI readable.
    "ENUM_NAME_OVERRIDES": {
        "StatementFileStatusEnum": "core.models.statements.file.StatementFile.STATUS_CHOICES",
        "StatementAdvanceTargetEnum": "core.serializers.statements._ADVANCE_TARGET_CHOICES",
        "IssueTriageStatusEnum": ["open", "in_review", "resolved", "dismissed"],
    },
}

SIMPLE_JWT = {
    # Short-lived access token + longer-lived, rotating refresh token — standard
    # JWT bearer pair per API Design Guidelines §8. Rotation + blacklist-after-
    # rotation means a stolen refresh token can only be replayed once before
    # it's rejected, without needing a separate revocation list to maintain by hand.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ── Refresh-token cookie (hybrid httpOnly approach, PLAN.md Checkpoint E) ──
# Only the refresh token moves to an httpOnly cookie — the access token
# stays in the response body/Authorization header (explicit decision: ease
# of dev/Swagger testing). SameSite=Lax works in both dev (frontend :5173,
# backend :8000 — cross-origin but same-SITE, since SameSite matching is by
# scheme+registrable-domain, not port) and prod (frontend/backend share one
# origin behind nginx, deploy/nginx.conf) without needing SameSite=None.
# Secure is tied to DEBUG since dev has no TLS — a Secure cookie would just
# be silently dropped over plain http://localhost.
REFRESH_TOKEN_COOKIE_NAME = "refresh_token"
REFRESH_TOKEN_COOKIE_SECURE = not DEBUG
REFRESH_TOKEN_COOKIE_SAMESITE = "Lax"
REFRESH_TOKEN_COOKIE_MAX_AGE = int(SIMPLE_JWT["REFRESH_TOKEN_LIFETIME"].total_seconds())

MIDDLEWARE = [
    # CorsMiddleware must be first — before any middleware that can generate
    # responses (SecurityMiddleware, CommonMiddleware) so preflight OPTIONS
    # requests get the CORS headers before being short-circuited.
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ── CORS (django-cors-headers) ─────────────────────────────────────────────────
# Covers the Vite dev server (:5173) and the deploy nginx proxy (:8080).
# In production, DJANGO_CORS_ALLOWED_ORIGINS should be set to the real domain.
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in env.list(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        default=[
            "http://localhost:5173",
            "http://localhost:8080",
            "http://127.0.0.1:5173",
        ],
    )
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("POSTGRES_DB", "appdb"),
        "USER": env.str("POSTGRES_USER", "appuser"),
        "PASSWORD": env.str("POSTGRES_PASSWORD", "apppass"),
        "HOST": env.str("POSTGRES_HOST", "postgres"),
        "PORT": env.str("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# File storage — SeaweedFS via its S3-compatible Filer gateway
# (docs/File_System_Structure.md, PLAN.md Checkpoint 0). One named storage
# per bucket/file-type — services/storage_backends.py owns the connection
# details read from the SEAWEED_* env vars above (_REQUIRED_ENV). "default"
# stays FileSystemStorage since nothing in this project uses Django's generic
# FileField storage; every real upload path picks one of the named storages
# below explicitly via services/file_storage.py.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "raw_statements": {
        "BACKEND": "services.storage_backends.RawStatementStorage",
    },
    "ocr_artifacts": {
        "BACKEND": "services.storage_backends.OcrArtifactStorage",
    },
    "normalized_artifacts": {
        "BACKEND": "services.storage_backends.NormalizedArtifactStorage",
    },
    "reference_data": {
        "BACKEND": "services.storage_backends.ReferenceDataStorage",
    },
}


# ── Redis / Celery / SSE (Checkpoint: async infra phase) ──────────────────────
# One Redis instance serves two independent purposes: Celery's broker (task
# queue) and the SSE event bus's pub/sub (services/event_bus.py,
# services/sse_tickets.py) — not added to _REQUIRED_ENV above since it has a
# working default, same pattern as POSTGRES_HOST.
REDIS_URL = env.str("REDIS_URL", "redis://redis:6379/0")

CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", REDIS_URL)
# No result backend: task completion is communicated to callers via the
# persisted StatementFile/Message rows plus an SSE event published from
# inside the task (core/tasks/*.py) — nothing ever calls .get()/.result on a
# task, so a result backend would be dead infrastructure.
CELERY_TASK_IGNORE_RESULT = True
# Forced True in tests (tests/conftest.py) so the pipeline can be exercised
# with an ordinary APIClient call and no live worker/broker.
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", False)
CELERY_TASK_EAGER_PROPAGATES = True

# Short-lived, single-use ticket TTL for GET /events/stream (core/views/events.py)
# — native EventSource can't set an Authorization header, and this project's
# access token is never cookie-based (core/authentication.py), so the stream
# is gated by a ticket minted just-in-time via POST /events/ticket instead.
SSE_TICKET_TTL_SECONDS = env.int("SSE_TICKET_TTL_SECONDS", 30)
